namespace MiniSpace.Services.Events.Core.Entities
{
    public enum Category
    {
        Music,
        Sports,
        Education,
        Science,
        Technology,
        Art,
        Business,
        Health,
        Charity,
        Social,
        Networking,
        FoodAndDrink,
        Travel,
        Outdoors,
        Fitness,
        Entertainment,
        Politics,
        Religion,
        Family,
        History,
        Literature,
        Fashion,
        Film,
        Gaming,
        Cultural,
        Environmental,
        PersonalDevelopment,
        Finance,
        Other
    }
}
