apps:
  - name: api-gateway
    script: dotnet MiniSpace.APIGateway.dll
    cwd: ../MiniSpace.APIGateway/src/MiniSpace.APIGateway/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5000

  - name: comments-service
    script: dotnet MiniSpace.Services.Comments.Api.dll
    cwd: ../MiniSpace.Services.Comments/src/MiniSpace.Services.Comments.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5009

  - name: email-service
    script: dotnet MiniSpace.Services.Email.Api.dll
    cwd: ../MiniSpace.Services.Email/src/MiniSpace.Services.Email.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5016

  - name: events-service
    script: dotnet MiniSpace.Services.Events.Api.dll
    cwd: ../MiniSpace.Services.Events/src/MiniSpace.Services.Events.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5008

  - name: friends-service
    script: dotnet MiniSpace.Services.Friends.Api.dll
    cwd: ../MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5012

  - name: identity-service
    script: dotnet MiniSpace.Services.Identity.Api.dll
    cwd: ../MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5004

  - name: mediafiles-service
    script: dotnet MiniSpace.Services.MediaFiles.Api.dll
    cwd: ../MiniSpace.Services.MediaFiles/src/MiniSpace.Services.MediaFiles.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5014

  - name: notifications-service
    script: dotnet MiniSpace.Services.Notifications.Api.dll
    cwd: ../MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5006

  - name: posts-service
    script: dotnet MiniSpace.Services.Posts.Api.dll
    cwd: ../MiniSpace.Services.Posts/src/MiniSpace.Services.Posts.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5013

  - name: reactions-service
    script: dotnet MiniSpace.Services.Reactions.Api.dll
    cwd: ../MiniSpace.Services.Reactions/src/MiniSpace.Services.Reactions.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5010

  - name: reports-service
    script: dotnet MiniSpace.Services.Reports.Api.dll
    cwd: ../MiniSpace.Services.Reports/src/MiniSpace.Services.Reports.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5005

  - name: students-service
    script: dotnet MiniSpace.Services.Students.Api.dll
    cwd: ../MiniSpace.Services.Students/src/MiniSpace.Services.Students.Api/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5007

  - name: web
    script: dotnet MiniSpace.Web.dll
    cwd: ../MiniSpace.Web/src/MiniSpace.Web/bin/Release/net8.0/publish
    max_restarts: 3
    env:
      ASPNETCORE_URLS: http://*:5606
