name: Sync to GitLab Repository

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  # Fetch all branches

      - name: Configuring git
        run: |
          git config --global user.email "voznesenskijandrej5@gmail.com"
          git config --global user.name "Andrii Voznesenskyi"

      - name: Adding GitLab remote repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          GITLAB_REPO="https://oauth2:${GITLAB_TOKEN}@gitlab.com/SaintAngeLs/distributed_minispace.git"
          if git remote get-url gitlab; then
            echo "Remote 'gitlab' already exists. Updating URL if needed."
            git remote set-url gitlab $GITLAB_REPO
          else
            git remote add gitlab $GITLAB_REPO
          fi

      - name: Push all branches to GitLab
        run: git push gitlab --all --force

      - name: Push all tags to GitLab
        run: git push gitlab --tags --force

      - name: Push pull requests to GitLab
        run: |
          # Fetch the pull request refs
          git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
          # Push each pull request ref to GitLab
          for ref in $(git for-each-ref --format='%(refname)' refs/remotes/origin/pr/*); do
            pr_ref=${ref#refs/remotes/origin/pr/}
            # Split the ref by / and get the PR number
            IFS='/' read -ra ADDR <<< "$pr_ref"
            pr_number=${ADDR[0]}
            # Check out the PR head branch
            git fetch origin pull/$pr_number/head:pr-$pr_number
            git checkout pr-$pr_number
            # Push the PR head branch to GitLab as a branch named pr-{PR number}
            git push gitlab pr-$pr_number:refs/heads/pr-$pr_number --force
          done
