name: Sync to GitLab Repositories

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPO: ${{ github.repository }}
      GITLAB_REPO_1: 'SaintAngeLs/distributed_minispace'
      GITLAB_REPO_2: 'distributed-asp-net-core-blazor-social-app/distributed_minispace'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  # Fetch all branches

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Sync Pull Requests and Issues to GitLab
        run: python sync_prs_issues.py

      - name: Configuring git
        run: |
          git config --global user.email "voznesenskijandrej5@gmail.com"
          git config --global user.name "Andrii Voznesenskyi"

      - name: Adding GitLab remote repository 1
        run: |
          GITLAB_REPO="https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/SaintAngeLs/distributed_minispace.git"
          if git remote get-url gitlab1; then
            echo "Remote 'gitlab1' already exists. Updating URL if needed."
            git remote set-url gitlab1 $GITLAB_REPO
          else
            git remote add gitlab1 $GITLAB_REPO
          fi

      - name: Push all branches to GitLab 1
        run: git push gitlab1 --all --force

      - name: Push all tags to GitLab 1
        run: git push gitlab1 --tags --force

      - name: Adding GitLab remote repository 2
        run: |
          GITLAB_REPO="https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/distributed-asp-net-core-blazor-social-app/distributed_minispace.git"
          if git remote get-url gitlab2; then
            echo "Remote 'gitlab2' already exists. Updating URL if needed."
            git remote set-url gitlab2 $GITLAB_REPO
          else
            git remote add gitlab2 $GITLAB_REPO
          fi

      - name: Push all branches to GitLab 2
        run: git push gitlab2 --all --force

      - name: Push all tags to GitLab 2
        run: git push gitlab2 --tags --force

      - name: Push pull requests to GitLab 1
        run: |
          # Fetch the pull request refs
          git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
          # Push each pull request ref to GitLab 1
          for ref in $(git for-each-ref --format='%(refname)' refs/remotes/origin/pr/*); do
            pr_ref=${ref#refs/remotes/origin/pr/}
            # Split the ref by / and get the PR number
            IFS='/' read -ra ADDR <<< "$pr_ref"
            pr_number=${ADDR[0]}
            # Check out the PR head branch
            git fetch origin pull/$pr_number/head:pr-$pr_number
            git checkout pr-$pr_number
            # Push the PR head branch to GitLab 1 as a branch named pr-{PR number}
            git push gitlab1 pr-$pr_number:refs/heads/pr-$pr_number --force
          done

      - name: Push pull requests to GitLab 2
        run: |
          # Fetch the pull request refs
          git fetch origin +refs/pull/*:refs/remotes/origin/pr/*
          # Push each pull request ref to GitLab 2
          for ref in $(git for-each-ref --format='%(refname)' refs/remotes/origin/pr/*); do
            pr_ref=${ref#refs/remotes/origin/pr/}
            # Split the ref by / and get the PR number
            IFS='/' read -ra ADDR <<< "$pr_ref"
            pr_number=${ADDR[0]}
            # Check out the PR head branch
            git fetch origin pull/$pr_number/head:pr-$pr_number
            git checkout pr-$pr_number
            # Push the PR head branch to GitLab 2 as a branch named pr-{PR number}
            git push gitlab2 pr-$pr_number:refs/heads/pr-$pr_number --force
          done
