name: Sync to GitLab Repositories

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  Sync:
    runs-on: ubuntu-latest
    env:
      GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPO: ${{ github.repository }}
      GITLAB_REPO_1: 'SaintAngeLs/distributed_minispace'
      GITLAB_REPO_2: 'distributed-asp-net-core-blazor-social-app/distributed_minispace'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0  # Fetch all branches

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Configuring git
        run: |
          git config --global user.email "voznesenskijandrej5@gmail.com"
          git config --global user.name "Andrii Voznesenskyi"

      - name: Remove .gitlab-ci.yml for SaintAngeLs repository
        run: |
          if [ "${{ github.repository }}" = "SaintAngeLs/distributed_minispace" ]; then
            echo "Removing .gitlab-ci.yml from the deployment package."
            rm -f .gitlab-ci.yml
          fi

      - name: Adding GitLab remote repository 1
        run: |
          GITLAB_REPO="https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/SaintAngeLs/distributed_minispace.git"
          git remote add gitlab1 $GITLAB_REPO || git remote set-url gitlab1 $GITLAB_REPO

      - name: Push all branches to GitLab 1
        run: git push gitlab1 --all --force

      - name: Push all tags to GitLab 1
        run: git push gitlab1 --tags --force

      - name: Adding GitLab remote repository 2
        run: |
          GITLAB_REPO="https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/distributed-asp-net-core-blazor-social-app/distributed_minispace.git"
          git remote add gitlab2 $GITLAB_REPO || git remote set-url gitlab2 $GITLAB_REPO

      - name: Push all branches to GitLab 2
        run: git push gitlab2 --all --force

      - name: Push all tags to GitLab 2
        run: git push gitlab2 --tags --force
