name: OSSAR Analysis

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '41 6 * * 2'

permissions:
  contents: read

jobs:
  OSSAR-Scan:
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run OSSAR
      uses: github/ossar-action@v1
      id: ossar

    - name: Upload OSSAR results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.ossar.outputs.sarifFile }}
