name: SecurityCodeScan Analysis

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]
  schedule:
    - cron: '45 14 * * 3'

jobs:
  apigateway:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.APIGateway/MiniSpace.APIGateway.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.APIGateway/MiniSpace.APIGateway.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Comments/MiniSpace.Services.Comments.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Comments/MiniSpace.Services.Comments.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Email/MiniSpace.Services.Email.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Email/MiniSpace.Services.Email.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Events/MiniSpace.Services.Events.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Events/MiniSpace.Services.Events.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_friends:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Friends/MiniSpace.Services.Friends.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Friends/MiniSpace.Services.Friends.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_identity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Identity/MiniSpace.Services.Identity.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Identity/MiniSpace.Services.Identity.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_mediafiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.MediaFiles/MiniSpace.Services.MediaFiles.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.MediaFiles/MiniSpace.Services.MediaFiles.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Notifications/MiniSpace.Services.Notifications.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Notifications/MiniSpace.Services.Notifications.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_organizations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Organizations/MiniSpace.Services.Organizations.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Organizations/MiniSpace.Services.Organizations.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Posts/MiniSpace.Services.Posts.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Posts/MiniSpace.Services.Posts.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_reactions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Reactions/MiniSpace.Services.Reactions.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Reactions/MiniSpace.Services.Reactions.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Reports/MiniSpace.Services.Reports.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Reports/MiniSpace.Services.Reports.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  services_students:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Students/MiniSpace.Services.Students.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Students/MiniSpace.Services.Students.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Web/MiniSpace.Web.sln
      - name: Build
        run: dotnet build --no-restore MiniSpace.Web/MiniSpace.Web.sln
      - name: Convert sarif for uploading to GitHub
        uses: security-code-scan/security-code-scan-results-action@v1
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
