name: SecurityCodeScan Analysis

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]
  schedule:
    - cron: '45 14 * * 3'

jobs:
  apigateway:
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.APIGateway/src/MiniSpace.APIGateway/MiniSpace.APIGateway.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.APIGateway/src/MiniSpace.APIGateway/MiniSpace.APIGateway.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_comments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Comments/src/MiniSpace.Services.Comments.Api/MiniSpace.Services.Comments.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Comments/src/MiniSpace.Services.Comments.Api/MiniSpace.Services.Comments.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Email/src/MiniSpace.Services.Email.Api/MiniSpace.Services.Email.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Email/src/MiniSpace.Services.Email.Api/MiniSpace.Services.Email.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_events:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Events/src/MiniSpace.Services.Events.Api/MiniSpace.Services.Events.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Events/src/MiniSpace.Services.Events.Api/MiniSpace.Services.Events.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_friends:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Api/MiniSpace.Services.Friends.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Api/MiniSpace.Services.Friends.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_identity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/MiniSpace.Services.Identity.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/MiniSpace.Services.Identity.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_mediafiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.MediaFiles/src/MiniSpace.Services.MediaFiles.Api/MiniSpace.Services.MediaFiles.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.MediaFiles/src/MiniSpace.Services.MediaFiles.Api/MiniSpace.Services.MediaFiles.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_notifications:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Api/MiniSpace.Services.Notifications.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Api/MiniSpace.Services.Notifications.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_organizations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Api/MiniSpace.Services.Organizations.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Api/MiniSpace.Services.Organizations.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Posts/src/MiniSpace.Services.Posts.Api/MiniSpace.Services.Posts.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Posts/src/MiniSpace.Services.Posts.Api/MiniSpace.Services.Posts.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_reactions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Reactions/src/MiniSpace.Services.Reactions.Api/MiniSpace.Services.Reactions.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Reactions/src/MiniSpace.Services.Reactions.Api/MiniSpace.Services.Reactions.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_reports:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Reports/src/MiniSpace.Services.Reports.Api/MiniSpace.Services.Reports.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Reports/src/MiniSpace.Services.Reports.Api/MiniSpace.Services.Reports.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  services_students:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Services.Students/src/MiniSpace.Services.Students.Api/MiniSpace.Services.Students.Api.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Services.Students/src/MiniSpace.Services.Students.Api/MiniSpace.Services.Students.Api.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif

  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v1
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '3.1.x'
      - name: Install .NET 8.x
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0
      - name: Set up projects for analysis
        uses: security-code-scan/security-code-scan-add-action@v1
      - name: Restore dependencies
        run: dotnet restore MiniSpace.Web/src/MiniSpace.Web/MiniSpace.Web.csproj
      - name: Build
        run: dotnet build --no-restore MiniSpace.Web/src/MiniSpace.Web/MiniSpace.Web.csproj
      - name: Convert sarif for uploading to GitHub
        run: |
          dotnet tool install --global Sarif.Multitool --version 2.3.10
          sarif multitool merge --output results.sarif --force **/*.sarif
          node .github/convert.js results.sarif
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: filtered-results.sarif
