name: Check for appsettings.json Files and Potential Secrets Exposure

on: [push, pull_request]

jobs:
  check-appsettings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check for appsettings.json files
      run: |
        # Get a list of all added or modified files in the commit
        FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})

        # Check if any of the files match the pattern "appsettings*.json"
        if echo "$FILES" | grep -qE "appsettings.*\.json"; then
          echo "Found appsettings.json file changes"
          # Notify the commit author
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%ae')
          MESSAGE="Warning: Commit contains appsettings.json file changes which are not allowed and have been removed."
          echo "$MESSAGE"
          curl -s --user "api:$GITHUB_TOKEN" \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header "Content-Type: application/json" \
            --data "{ \"title\": \"Commit contains appsettings.json file changes\", \"body\": \"$MESSAGE\", \"assignees\": [\"$COMMIT_AUTHOR\"] }"

          # Remove appsettings.json files
          git rm --cached $(echo "$FILES" | grep -E "appsettings.*\.json")
          git commit -m "Removed appsettings.json files from commit"
          git push

          # Exit with a failure status to prevent the commit from being pushed
          exit 1
        else
          echo "No appsettings.json file changes found"
        fi

    - name: Scan for potential secrets exposure
      run: |
        # Scan for secrets in the added or modified files
        SECRET_PATTERNS="password|secret|key|token|credential"
        SECRET_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | xargs grep -E -i $SECRET_PATTERNS || true)
        
        if [ -n "$SECRET_FILES" ]; then
          echo "Potential secrets exposure found in the following files:"
          echo "$SECRET_FILES"
          # Notify the commit author
          COMMIT_AUTHOR=$(git log -1 --pretty=format:'%ae')
          MESSAGE="Warning: Potential secrets exposure found in the following files:\n$SECRET_FILES"
          echo "$MESSAGE"
          curl -s --user "api:$GITHUB_TOKEN" \
            --request POST \
            --url https://api.github.com/repos/${{ github.repository }}/issues \
            --header "Content-Type: application/json" \
            --data "{ \"title\": \"Potential secrets exposure\", \"body\": \"$MESSAGE\", \"assignees\": [\"$COMMIT_AUTHOR\"] }"

          # Exit with a failure status to prevent the commit from being pushed
          exit 1
        else
          echo "No potential secrets exposure found"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
